### ISSUE TITLE
Continuous integration and deployment

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#101]
Set up the automatic running of a test suite, and publish Docker images whenever a commit is pushed to GitHub. 
This is currently performed manually, so it is important to implement it for future maintainability. 

GitHub Actions will be used for this purpose, which is free for open-source projects.

**Comment by onyb** [comment]
Fixed in [v0.18.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.18.0).
