### ISSUE TITLE
Keep computations' history

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#103]
It would be helpful to keep a record of the computations that created a PDT, so if one wants to replicate the same computations with other data, it would be much easier. 
It might require to introduce an embedded database to store unstructured data. Also implement a view on the frontend to display the computation history. 
It will also lay the groundwork for future enhancements that require persistence.

**Comment by FatimaPillosu** [comment]
Esti has commented:

It would be nice to have some option to save the "inputs" when we create the ascii database (definition of input observations, predictors folder, predictant folder, dates from the calendar, predictors...) for the next access to the software. Especially at the beginning, when we are testing a new database or a new variable, it can be quite slow to introduce the inputs every day, and in general, we only have to modify an option or two in the inputs in every test. We could do it in two different ways @FatimaPillosu @ATimHewson @onyb @AugustinVintzileos , feel free to comment which option is better:

Open the settings used from the previous session when we open a new session.
Add an option in the Module 1 of the software to "save settings" to a text file that can be read any time when we open a new session, so if we choose the option of reading the file, we do not need to introduce the inputs by hand.
This option includes also the definition of the predictors, as we have plenty of predictors and it is quite painful to add one by one every time that open a new session of the software.

**Comment by onyb** [comment]
Added in [v0.20.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.20.0). Please let me know if you have questions regarding how to use it.
