### ISSUE TITLE
Include WT bias in the mapping function

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#104]
this is related to issue #106 
For each MFs, it would be very helpful to calculate the bias correction (formula to be provided) and other statistics to be defined.
See, for example, the following picture where the number on the side represents the grid-scale bias for this WT.
![image](https://user-images.githubusercontent.com/39411276/94741751-83f2a280-036c-11eb-9522-4a427639e8ab.png)

**Comment by onyb** [comment]
Fixed in [v0.17.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.17.0).
