### ISSUE TITLE
Framework to compare WTs

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#105]
It would be very useful to have a framework in the software where it would be possible to display the WTs from two different DTs. This would be a very useful feature to have, for example, in case of evaluating whether or not change DT when there is a new forecast cycle. It will also be very useful to be able to highlight those WTs where the user thinks there is some significant difference in the WTs, and being able to display that in the DT. This will be a very useful diagnostic tool.

Define the UX of the framework to use for comparisons. Provide a way to load existing DT into an interactive comparison tool.

**Comment by onyb** [comment]
Added in [v0.19.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.19.0). It basically allows the user to spin up as many GUI windows as he/she wants, like this:

```
$ ./ecPoint-Calibrate-0.19.0.AppImage         # first window
$ ./ecPoint-Calibrate-0.19.0.AppImage --fork  # subsequent windows
```

I'll close this for now, but if the fix is not enough, please feel free to reopen it.
