### ISSUE TITLE
Summary of the biases of all WTs

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#106]
It would be very useful to have also a summary of the biases for all the WTs as a diagnostic tool.

![image](https://user-images.githubusercontent.com/3684187/97452676-48c89c80-1935-11eb-89ab-6e7d142fc45d.png)

@ATimHewson , could you please add the equation to compute the bias for each WT?

**Comment by ATimHewson** [comment]
The (gridbox) bias, for each weather type, where "1" means unbiased, is simply based on an FER mean, as given by:

1 + [(Sum of all FER values used to define that weather type's mapping function)/(the number of these FER values)]

I would recommend plotting the bias, in quite large black font, in the top right corner of a mapping function plot.

**Comment by onyb** [comment]
Depends on https://github.com/esowc/ecPoint-Calibrate/issues/104

**Comment by onyb** [comment]
Fixed in [v0.17.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.17.0).
