### ISSUE TITLE
Allow to remove the predictant as a predictor

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#111]
Edited by Esti:
Currently, the predictand is a predictor by default, but it would be good to have the option of "untick" that variable as a predictor. For example, in the 2m temperature calibration, we could consider using the skin temperature as a predictor, instead of the 2m temperature.

----------
Edited by Fatima
@onyb, on the basis of my comment below, could we change this in this way:

- [x] Rainfall case (accumulated predictand): we do need to compute the predictand for the threshold selection, but also, in this case, we might not need the predictand also as a predictor. Could we make sure the predictand is always computed, but we allow the possibility to untick it as a predictor? Maybe we just don't let the user delete the computation.

- [x] Temperature case (not accumulated predictand): we don't need to compute the predictand for the threshold selection, and we might not need the predictand also as a predictor. Thus, I think we don't need to do anything in this case; we don't need to constrain its computation. Could we completely remove the first computation in this case?

**Comment by FatimaPillosu** [comment]
Hi @EstiGascon,
Thanks for this comment. The reason why we did this is that in the case of precipitation (accumulated predictand), we always have to compute the predictand to select a minimum threshold. This is not the case for temperature (not accumulated predictand).

@onyb, could we change this in this way: 

- [ ] **Rainfall case (accumulated predictand):** we do need to compute the predictand for the threshold selection, but also, in this case, we might not need the predictand also as a predictor. Could we make sure the predictand is always computed, but we allow the possibility to untick it as a predictor? Maybe we just don't let the user delete the computation.

- [ ] **Temperature case (not accumulated predictand):** we don't need to compute the predictand for the threshold selection, and we might not need the predictand also as a predictor. Thus, I think we don't need to do anything in this case; we don't need to constrain its computation. Could we completely remove the first computation in this case?

**Comment by onyb** [comment]
Fixed in [v0.17.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.17.0).
