### ISSUE TITLE
Summary of the checks done on the release 0.11.2 

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#121]
1. Checks passed positively (the relative issues ):
- [x] It is possible now to add negative adding factor.
- [x] Replace inf with 9999 while saving breakpoints csv
- [x] Display total number of observations in histogram, during post-processing
- [x] Now we can select between parquet and ascii table.
- [x] The parquet option works really well. The files does not only reduces in size of 4.3 times, but the computations are noticeably much faster.

____________________________________________________________________________________________________

2. Checks passed negatively or new bugs found:
- [x] In the computations section, please, change "Multiplication Factor" with "Multiplying Factor"; and "Addition Factor" with "Value to Add". The English is not correct, so we need to improve it.
- [x] Please, see issue #119
- [x] Please, see issue #120 
- [x] The logs are again not displayed in the GUI. I think, we will get rid of this feature, as it seems to not work properly most of the time. Now there is also a button to pause the computations but it doesn't work.
- [x] I couldn't see where to select (or deselect) some PDT variables to not appear in the calibration process.

____________________________________________________________________________________________________

3. Checks passed positively but can still be improved:
- [x] In the definition of the computations, by chance I added a short name for the predictor (tp) that it was the same of the input parameter (tp), and the space became red. It is correct, but I didn't know why it was appearing red. I guessed it. It would be nice if a red message appears telling the user what it is happening, something like "Predictors short names cannot be the same of the input parameters names!"
- [x] Please, check what would happen if a decimal multiplying factor is entered. If the user enters, for example, 0.5, this means a division by 2 is requested; if 1.5 is entered, this means multiplying by 3 and diving by 2; etc. 
- [x] I changed the name of the input solar radiation parameter (I called it cdir, as called in our archive at ECMWF) and the software, as expected, showed me all the variables because there was no variables called sr. The system implemented needs works but it needs to be changed because there are different solar radiation variables and they can be called in many ways. A solution could be checking the name variable in the grib file and check whether the words "solar" and "radiation" are contained in the name, and if so, only those are shown in the list of possible variables. This should not be complicated to do.
- [x]  when saving the file containing the forecast error (ratios), I would not call them by default "errors.csv". I would call them "FERs.csv" or "FEs.csv" so it is possible to distinguish them.

_________________________________________________________________________________________________

The issues under (1) have been already closed by @FatimaPillosu.
The issues under (2) and (3) need to be revised.@onyb, please, open the relevant issues.

Cheers,

Fatima

**Comment by onyb** [comment]
All issues in section 2 should be resolved now. Can you please verify if they are still valid and check the right boxes?

Regarding selecting / deselecting PDT variables, maybe you're looking for the **Predictor?** column in the following image:

<img width="1125" alt="Screenshot 2020-11-13 at 01 59 45" src="https://user-images.githubusercontent.com/3684187/99014867-ea660580-2553-11eb-9e9f-c41c01b267ed.png">

Regarding section 3, I have verified that multiplying/addition factors indeed accept decimal values. I also renamed "errors.csv" to "FER.csv" / "FE.csv". Actually, I realize now that I forgot the "s" in "FERs.csv" (as you had suggested), so let me know if you would like me to add that.

**Comment by onyb** [comment]
All containing issues fixed. Closing this.
