### ISSUE TITLE
Check the file BreakPoints.csv 

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#122]
Please, check that the file BreakPoints.csv with the -9999 and 9999 can be correctly uploaded back in the software. Or do we need the version with -inf and inf. 
If this is the case, please keep both versions.

- The version with -inf and inf to be used with the software in subsequent calibrations.
- The version with -9999 and 9999 to be used in the software that computes the forecasts operationally.

**Comment by FatimaPillosu** [comment]
Can we call this file BreakPointsWT.csv? so it is clear already from the name what these breakpoints refer to.

**Comment by onyb** [comment]
Fixed in [v0.15.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.15.0). Feel free to reopen if the issue is still not solved, or if you have questions.
