### ISSUE TITLE
cannot apply the Kolmogorov-Smirnov test for the second variable in the tree in v.0.12.0

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#126]
After applying the Kolmogorov-Smirnov test to the first variable in the decision tree, we tried to apply the test for a branch of the first variable, to create the breakpoints of the second variable. But the software does not allow to "click" and select this second variable, only in the first one (in the option "Select the level at which breakpoints must be suggested"). You can see the variable in the drop-down list, but when you click on it, it is not selected. 

The test was done with a "parquet" file in the software version 0.12.0

**Comment by AugustinVintzileos** [comment]
An example of the output file (parquet) containing SKT (skin temperature), 2T (2-meter temperature), and BLH (boundary layer height) can be found in  /vol/highlander

**Comment by onyb** [comment]
@AugustinVintzileos Can you please upload this parquet file to our shared Google Drive?

**Comment by AugustinVintzileos** [comment]
Done. I created a subdirectory: Highlander in which I uploaded the file. Please let me know if you have any problems reading it.
________________________________

**Comment by onyb** [comment]
It seems we had this bug since a long time. It only manifests itself when the split value in the input box is empty and the level is selected from the drop-down list.

It has been fixed in the [v0.12.1](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.12.1) release.
