### ISSUE TITLE
Save the settings from previous access 

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#132]
It would be nice to have some option to save the "inputs"  when we create the ascii database (definition of input observations, predictors folder, predictant folder, dates from the calendar, predictors...) for the next access to the software. Especially at the beginning, when we are testing a new database or a new variable, it can be quite slow to introduce the inputs every day, and in general, we only have to modify an option or two in the inputs in every test. We could do it in two different ways @FatimaPillosu @ATimHewson @onyb @AugustinVintzileos , feel free to comment which option is better:

1. Open the settings used from the previous session when we open a new session. 
2. Add an option in the Module 1 of the software to "save settings" to a text file that can be read any time when we open a new session, so if we choose the option of reading the file, we do not need to introduce the inputs by hand.

This option includes also the definition of the predictors, as we have plenty of predictors and it is quite painful to add one by one every time that open a new session of the software.

**Comment by FatimaPillosu** [comment]
This has been discussed in the last review meeting, and relates to an already existing issue (#103). I will close this issue, but I will copy your comment in here for Anirudha to read it.
