### ISSUE TITLE
Allow to see the mapping functions of previous nodes in the decision tree

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#134]
When we create new branches in the decision tree, we are not allowed to check the mapping function of the previous node (variable) in the decision tree. Sometimes it is necessary to have this option to review our decisions, but now we can only do it if we remove the new branches. See plot for reference. 
![Mapping_function_branches](https://user-images.githubusercontent.com/69871426/101374262-da68e980-38a5-11eb-9933-9ade00bb109c.png)

**Comment by FatimaPillosu** [comment]
Hi @Esti,
this has been discussed with @onyb at the last review meeting. this will be part of one of the new features to deliver soon.

**Comment by onyb** [comment]
Fixed in [v0.19.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.19.0).
