### ISSUE TITLE
defining bins (minor)

### ISSUE THREAD

**Issue by AugustinVintzileos** [esowc/ecPoint-Calibrate#136]
We need to type the bins in the format 0.5. Typing .5 is creating an error message.

**Comment by onyb** [comment]
I think the advantage of using `0.5` over `.5` is more clear when you consider negative floating-point numbers. For example,  using `-0.5` is more common than `-.5`.

**Comment by AugustinVintzileos** [comment]
Maybe state the format near this entry because there are many people used to type -.5 instead -0.5. I guess an error message indicating the correct format would be enough.

________________________________

**Comment by onyb** [comment]
Fixed in [v0.18.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.18.0).
