### ISSUE TITLE
Validation of values for the predictor's thresholds

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#139]
The thresholds for each predictor should be consecutive to not have gaps in the analysis. 

- We should have Thr_L in the first row always as -inf, in the case the variable is linear
- We should have Thr_H in the last row always as +inf, in the case the variable is linear
- The Thr_L in a row (X) should be the same of Thr_H in the row (X-1), in both cases (linear and circular variables)
- Thr_L should be < max(var) & Thr_L < Thr_H, in the first row of a circular variable
- Thr_H should be > min(var), in the first row of a circular variable
- Thr_L in the first row should be the same of Thr_H in the last row, in the case of a circular variable
- from line 2 to last line Thr_L < Thr_H, in both cases (linear and circular variable)

![image](https://user-images.githubusercontent.com/39411276/102098106-b023a880-3e1e-11eb-977b-0ac57c50b0aa.png)

**Comment by FatimaPillosu** [comment]
Introduce in the post-processing page whether a predictor is circular or not, and the period.

**Comment by ATimHewson** [comment]
I agree with Fatima's last post except that in the fourth bullet it should say ....Thr_L > Thr_H....

**Comment by onyb** [comment]
Added in [v0.19.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.19.0).
