### ISSUE TITLE
Be able to add negative values in the manual splitting 

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#140]
When we use the tool of splitting a predictor with breakpoints manually (instead of using the Kolmogorov test), currently we are not allowed to introduce negative values (see attachment). However, we will need this capability because many predictors contain negative values as well. 
![Splitting_tool](https://user-images.githubusercontent.com/69871426/102203325-57a4e780-3ec0-11eb-81e7-49af1477196c.png)

**Comment by ATimHewson** [comment]
This seems like a bug to me, that should be assigned top priority, but up to you Esti how you classify (based on how restrictive it is for you).

**Comment by EstiGascon** [comment]
Thanks Tim. Yes, I put it like a bug at the beginning, but as we had worked until now with that...I changed to enhancement. After yesterday´s conversation and the questions about the Kolmorov test, yes, this probably should be a  bug, as we need to use it more frequently

**Comment by FatimaPillosu** [comment]
Now there is no due date for bugs, as they will continue to appear through the whole project. So, please, feel free to keep adding issue with the "Bug" label if needed. 
This is not indeed an enhancement, as it has to be corrected. Enhancements are for things that are working and could be further improved. 
I'm sure @onyb will be able to correct it soon.

**Comment by onyb** [comment]
Fixed in [v0.18.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.18.0).
