### ISSUE TITLE
Summary Pending Issues (January 2021)

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#143]
- [x] Adding the possibility to extract metadata from the new observations' format to be added in the point data table (e.g. observations units).

- [ ] Add latitude and longitude as computations in FER and FE. They are not computations, strictly speaking, there are not computations to do. You just need to allow to use the column displaying the observations' lat/lon already displayed in the PDT as predictors in the creation of the decision tree. Those would be circular variables. 
- [x] We don't have the possibility to save a log that contains the settings of a specific run. It would be nice to have that to not have to repeat that.
- [ ] When I'm running some calculations, the bottom to stop the computations doesn't work. The bottom works in version 0.18.0 however and it seems that the computations stop. However, on the console, the computations clearly keep running. If this is too difficult to fix, I would then eliminate the button to stop the computations. Even when I come back to the home menu, I can see in the console that the computations keep running. 
- [ ] Plus, there's no way to come back to a previous step (e.g. Input parameters, or Computations), so I have to go back to Home and start all the computations from scratch, which is not very practical. It would be nice to be able to stop the computations and be able to go back to the settings and change them if need them, and then restart from the beginning of the computations. 
- [ ] If computing an ascii PDT table, the computations are getting stuck randomly, even if I compute only one predictor (e.g tp). But there is no error displayed. The computations simply stop without an error. This does happen also with parquet. This happens with version 0.19.0, not with previous versions. However, I cannot reproduce the error. I closed the software and it worked fine after that.
- [ ] The way the variables are selected as circular or not is really cool. But, I see I can select for example TP, put whatever range and the software will consider TP circular. As this could be error-prone if the user doesn't realize that have selected the wrong variable, I would suggest, for example, we change the colour of the variables that are considered circular or we highlight them somehow, so they will be more visible and hopefully, the user will be more aware of what he/she is doing.
- [ ] Regarding the same topic, in the table the last column indicates the "Period". I think this is redundant and I would eliminate it. What I think it would be very interesting, is to remind the user what are the units of the predictors because the values that the user will insert depend on that. Thus, the units could be displayed next to the name of the predictors, e.g. LST (hours from 0 to 24), TP (mm), etc. 
- [ ] I love the button "View Metadata". It would be very useful though if the first 20 lines of the actual numerical values could be displayed as well. 
- [ ] I would put a note just below "Input the threshold breakpoints in the following spreadsheet:" saying "For circular variables: the first thrL has to be the same of the last thrH". I forgot and I kept keep getting red bins and I didn't know why! Perhaps, this is something that should be displayed for all the errors that are checked in the breakpoints, so the user not only knows where the error is but also which one is. 
- [ ] I like how you have solved the issue on how to display the histograms for not leaves. However, It doesn't work when the variable that is not a leaf is a circular variable. The image appears, but, it contains nothing. Indeed, in the title, it says for example (-inf<=TP<2) (18<=LST<18). Indeed, this is wrong and it would not display anything because no values satisfy this condition. In this case, even for circular variables, we should have (-inf<=LST<inf) because there is no selection for LST in that node. 
![image](https://user-images.githubusercontent.com/39411276/104212754-777eeb00-542d-11eb-8a75-5619f1256a4c.png)

- [ ] I tried to run the K-S test for the variable LST and it didn't work. I got the following message:
![image](https://user-images.githubusercontent.com/39411276/104213241-fbd16e00-542d-11eb-8c4a-76604e90faf2.png)

- [ ] If I don't want to select a circular variable, I cannot do it. FOr example, If I want to skip one linear variable, I select -inf and inf as breakpoints. I cannot do it for circular variables. Perhaps, if the range is 0 to 24, and in the break-points we select 0 and 24 and that is the only selection, then the software can assume that we want to ignore that variable. 
- [x] In the release notes about how to split the view, when you say use the command --fork, could you please add what exactly we need to type in the console. I have no idea how to use that command. 
________

Notes:
- A wonderful screen displaying metadata of computations. 
- The new three instantaneous fields for FER seem to work fine.
- It is possible now to not necessarily consider the predictand as a predictor as well. 
- Love how the default values for each predictor are displayed, including the ranges for the circular variables.

**Comment by ATimHewson** [comment]
For "bottom" in Fatima's post above read "button"!! ;)

**Comment by onyb** [comment]
> In the release notes about how to split the view, when you say use the command --fork, could you please add what exactly we need to type in the console. I have no idea how to use that command.

As discussed last time, you simply need to launch subsequent GUI windows like this:

```
./ecPoint-Calibrate-0.19.0.AppImage --fork
```

**Comment by FatimaPillosu** [comment]
I have created separate issues for the left tasks listed in this issue, so I will close this issue.
Cheers,
Fatima
