### ISSUE TITLE
Error when remove the option of the predictant to be a predictor 

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#144]
When we are defining the variables to create the ascii or parquet datatable, now we have the possibility of removing the Predictant as a Predictor, just removing the tick "x" in the Predictor column. However, if you do it, there will be an error in the calculation of the Forecast Errors. So for now, we have to keep the predictant as a predictor if we want to avoid that error. 
I have checked the versions v.0.17 and v.0.19 and it happened in both.

**Comment by FatimaPillosu** [comment]
@EstiGascon,
could you please send the precise error that is happening (e.g. crashing, error message, etc)? Otherwise, Ani cannot reproduce this problem.

**Comment by EstiGascon** [comment]
The structure of the list of predictors and the predictant has changed in the most recent versions so we do not have this issue anymore.
