### ISSUE TITLE
Error 500 does not give extra information like in other software versions

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#148]
In version 0.19, I noticed that the Error 500 does not say anything extra which can help you to fix the issue. So you can spend too much time checking what is happening. However, I tested the v.0.17. again and we had more info which helped us to fix the issue. I am not sure why this extra info disappears from previous versions, but it would be nice to have it again.

**Comment by onyb** [comment]
Fixed in [v0.21.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.21.0).
