### ISSUE TITLE
The software crashed (blank page) if you try to remove a variable in the middle of the list

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#149]
When you are creating the ascii or parquet file, first you have to select and define all the variables to be computed. It happened to me several times that when I want to remove a variable clicking in the "X" symbol and the variable is not at the end of the list, then the software crashes (no description of the error, just Error 500), the screen is just blank and I have to restart the software and define everything again from scratch.

**Comment by onyb** [comment]
Fixed in [v0.20.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.20.0).
