### ISSUE TITLE
Bias correction factor may be wrong

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#150]
![ERA5_FE_2mminT](https://user-images.githubusercontent.com/69871426/108993360-5e0ac900-7692-11eb-9907-42293d6ba5e2.png)
In the example, it looks like the value of the bias correction factor on the top of the mapping functions could be wrong. For example, I think that the value on the left plot should be lower. Could you double-check the computation of the correction factor? Maybe it is something related to the computation depending on if it is accumulated (FER) or instantaneous variable (FE).

**Comment by FatimaPillosu** [comment]
We have a meeting today with Anirudha, we'll discuss this later. Thanks for pointing this out @EstiGascon

**Comment by EstiGascon** [comment]
Hi Anirudha,

We have been testing the version 0.23.0 with the correction of this issue, but it is still something wrong. We think that it could be due to some outliers in the FE which makes the bias correction value look "wrong". Just to be sure that it does not happen, we think that the calculation of the mean bias correction (so the black number on the top right of the mapping function) should be calculated only for the range of values plotted on the mapping function. For example, in the plots above, the mean bias correction would be calculated just with the FE between -30 and 30, but if we have any other value below or above that range (i.e. 52 or -40), then they are not used in the calculation of the bias correction factor.

Also, be sure that the calculation of the bias correction factor corresponds to the mean of the FE, being FE = OBS - FC.

This is quite urgent, so I would appreciate if you could have a look as soon as possible. Many thanks in advance!
