### ISSUE TITLE
One cannot merge the nodes immediately below the root

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#155]
It is not possible to merge the nodes immediately below the root. This is a bug. Please, allow that.

**Comment by onyb** [comment]
To reproduce: add a breakpoint on the Root node, and then add another one at the same level.

**Comment by onyb** [comment]
While fixing this bug, I found out that there was another while introducing breakpoints manually. We were not making sure that the breakpoint is introduced in the right place (relative to other breakpoints).

Both these bugs have been fixed and will be available in the next release.

**Comment by onyb** [comment]
Fixed in [v0.28.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.28.0).
