### ISSUE TITLE
Option "Save breakpoints" in the Menu, does not work

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#156]
Augustin and I had the same problem. When we click on the "Save breakpoints" button on the software Menu, it works and you have the black screen with the message "Saving" but it never finishes even waiting 1 hour. 
The only way to go out from that windows is by closing the software, as I tried choosing another option in the menu or pressing "Esc" on the keyboard or "Reloading" the page, but nothing worked.

**Comment by EstiGascon** [comment]
Hi @onyb . Just tested the rest of the option from the menu ("Save operations", "Save WTs" and so on) and they do not work either, it has the message "Saving" for a while and then I have the error message of "Empty response from the server".

 This is quite **urgent** as  we need the files generated using these options to implement the ecPoint post-processing operationally this week.

Many thanks in advance.

**Comment by FatimaPillosu** [comment]
Hi @onyb,
I checked this problem on my side as well, and it is even funnier than it seems. Sometimes it just stays on "Saving...." as Esti said, and sometimes the error "Empty response from server" appears in the GUI (and no further error messages in the console appear). However, the files were created for me. I just saw it by chance. @AugustinVintzileos, @EstiGascon can you check whether the files were created for you?

 @onyb, any ideas on what might be causing this funny situation?

Cheers,

Fatima

**Comment by onyb** [comment]
Hi everyone. This should be fixed in the latest release.

**Comment by FatimaPillosu** [comment]
Hi @onyb ,
yes, this is resolved, so I will close the issue.
Cheers,
Fatima
