### ISSUE TITLE
Choosing variables for the KS-test

### ISSUE THREAD

**Issue by AugustinVintzileos** [esowc/ecPoint-Calibrate#157]
I do not have access to all variables when performing the KS-test. Here is the image:

![image](https://user-images.githubusercontent.com/72265581/111791039-35dd4700-8899-11eb-905e-db3a17e74bca.png)

We need a scroll down capacity when the list of variables is longer than the screen.

**Comment by onyb** [comment]
@AugustinVintzileos Can you please upload here the ASCII table, so I can reproduce on my side?

**Comment by AugustinVintzileos** [comment]
Done!

**Comment by AugustinVintzileos** [comment]
I just attached the file debugging.txt (it needed a .txt extension)

________________________________

**Comment by onyb** [comment]
@AugustinVintzileos I don't see the file. Can you try clicking on "Attach files by..." as shown below, then selecting your file?

<img width="878" alt="Screenshot 2021-03-19 at 17 53 51" src="https://user-images.githubusercontent.com/3684187/111815518-11ef2500-88dc-11eb-8ee4-abeaf264d630.png">

**Comment by AugustinVintzileos** [comment]
It's what I did. I even had to change the extension to .txt from .ascii because otherwise the file wasn't seen. I'll try again, any additional tips on what went wrong? Alternatively, I could send it to you by email

________________________________

**Comment by AugustinVintzileos** [comment]
did it work?

**Comment by AugustinVintzileos** [comment]
Can we upload files from ECMWF to github?

________________________________

**Comment by onyb** [comment]
I'm afraid it doesn't work. Can you please email it to me instead?

**Comment by AugustinVintzileos** [comment]
just shared the file to your gmail account
________________________________

**Comment by FatimaPillosu** [comment]
Hi @onyb ,
yesterday I spoke with Augustin, and this was an user error. So I will close this issue.
Cheers,
Fatima
