### ISSUE TITLE
Leakage of variables

### ISSUE THREAD

**Issue by AugustinVintzileos** [esowc/ecPoint-Calibrate#158]
I am loosing variables when I try to select one for the KS-test. This happens after a few cycles of growing and pruning branches. Example. For the tree:

![image](https://user-images.githubusercontent.com/72265581/112154210-6c2d0600-8bba-11eb-9ec9-01c2245eb12b.png)

When I try to do a KS-test at the SKT level I am getting: 

![image](https://user-images.githubusercontent.com/72265581/112154350-91ba0f80-8bba-11eb-99c2-7479988fbd5d.png)

from where a lot of variables are missing e.g., FAL, LCC, and CAPE

My intuition is that it is happening  when collapsing branches for testing new variables.

**Comment by EstiGascon** [comment]
We had a meeting this afternoon to discuss this issue, and we found out something which could affect (not sure how much, but it is a bug, fur sure). Let's explain it with the following plot 
![Bug_tree](https://user-images.githubusercontent.com/69871426/112185798-75d55e80-8bf8-11eb-8c13-4b2e4ac898dd.png)

The final weather type names are OK. However, if you see the Root weather type or the different weather types in the 2 LSM branches, they are incorrect as well. For example, the root WT is here 2010000000, when it should be just 0000000000, with any digit different to zero.

**Comment by FatimaPillosu** [comment]
Hi @onyb 
I spoke yesterday with Augustin and we realized that this was a user error. We know now what is causing it, so I will close this issue.
Cheers,
Fatima
