### ISSUE TITLE
When we do not divide a variable in different branches, we want to see see the node with the values -inf<VAR<inf

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#159]
During the decision tree preparation process, sometimes we do not divide a parameter into different branches for a specific branch of the previous variable. If we see in the plot attached, we have 3 variables in this order: LSM, SDFOR and SR24. For the branch of LSM<0.5, we do not want to divide the second variable into branches, so we will have only 1 branch with the values -inf<SDFOR<inf. 
Then, we divide the branch again with the following variable "SR24h". However, in the plot, we cannot see the vertical straight line of 1 branch coming from LSM <0.5 to the SDFOR variable (so the node with the SDFOR variable does not exist). This is a bit confusing because now we have SDFOR for LSM<0.5 and SR24h for LSM>0.5 at the same horizontal level in this plot, so it can confuse the user to know if he/she is working with the second parameter or the third. Even if the final weather type is correct, it would be more helpful to have the corresponding SDFOR node with the interval -inf to inf. 

![Bug_tree](https://user-images.githubusercontent.com/69871426/112187318-e6c94600-8bf9-11eb-916a-3468b492a576.png)

**Comment by FatimaPillosu** [comment]
Hi @onyb,
I think what Esti is suggesting is the way we use to plot the predictors that had no breakpoints. If I remember correctly, we decided instead for this current option (not plotting them, and instead plot the nodes with different colours) to keep the DT more compact. Speaking with @AugustinVintzileos yesterday gives me the impression that he is ok with the current way of displaying the nodes with no breakpoints but he might not dislike the implementation of Esti's suggestion. 
@onyb, could you advise how long would it take you to implement this change? In case it is too long, I would be inclined to move it to priority 3, as this is not a problem that would block the work of Esti and Augustin. So we solve the other more important issues first, and then we address this issue later.

**Comment by onyb** [comment]
TODO: we need to hide the nodes with thresholds same as the range, in case of circular variable.

**Comment by onyb** [comment]
Fixed in [v0.28.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.28.0).
