### ISSUE TITLE
Add ability to move predictors positions in the DT

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#160]
Hi @onyb,

this content of this issue was discussed with @Augustin yesterday, and it was triggered by his previous issues that now are closed because we found they were not actual bugs in the software.
At the moment, this is what happens. Let's say I have pred1, pred2, and pred3 in position 1, 2 and 3 in the DT, respectively. However, I want to analyse another order for the predictors. Let's say I want to put pred2 in position 3 and pred3 in position 2. In the tables that display the breakpoints in the GUI, the name of the columns will be updated, but their content won't. This means that the breakpoints defined for the pred2 will be assigned to pred3 and vice-versa. 
With Augustin, we were discussing yesterday that it would be nice to have the following solution. We would like to be able to move the predictors up and down in the top list and change the values of the breakpoints to -inf and inf for all the predictors that come afterwards. The predictors that come before do not change. 
@ATimHewson suggested this morning to have a message that will alert the user that losses in the work done so far will happen (because the breakpoints for all the predictors that come afterwards will be deleted). 
This issue doesn't block us. @AugustinVintzileos  has a way to do this same job by opening different windows. So, I won't put it as priority 1. However, we did agree that this is a nice feature to have so we don't have to open trillions of windows at the same time. Therefore, I will put this as a priority 2 because everyone would benefit from having this feature.
@onyb, could you please advice how long would it take you to implement this?
Cheers,
Fatima

**Comment by onyb** [comment]
Fixed in [v0.27.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.27.0). Closing this issue for now, but if you need further improvements, feel free to reopen.
