### ISSUE TITLE
The button that is supposed to stop the computation of the point data table doesn't work

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#162]
When I'm running some calculations, the button to stop the computations doesn't work. When I press, it seems that the computations stop. However, on the console, the computations clearly keep running. Even when I come back to the home menu, I can see in the console that the computations keep running. If this is too difficult to fix, I would then eliminate the button. However, it would be nice to be able to stop the computations and be able to go back to the settings and change them if needed, and then restart from the beginning of the computations.

**Comment by onyb** [comment]
Fixed in [v0.28.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.28.0). Please see release notes for more info.
