### ISSUE TITLE
Make units of predictors accessible to the module of the software that creates the DT

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#163]
At the moment the units of the predictors are not easily parseable from the point data table in ascii format. It would be very nice if we could have a way to make them accessible to the module of the software that computes the DT because it will be very useful the user is reminded of them. 
For example, when the user has to specify the period of the circular variables, the values that the user will insert depend on that. Thus, the units could be displayed next to the name of the predictors, e.g. LST (hours from 0 to 24), TP (mm), etc. They could be displayed also in the D-stat/pvalue diagrams in the K-S test.

**Comment by onyb** [comment]
Fixed in [0.27.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.27.0).
