### ISSUE TITLE
Error when plotting the mapping function for a circular variable

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#165]
When a circular variable is not a leaf or there is no selection of breakpoints for that variable, there is an error when displaying the mapping function. It selects the same value for the thr_L and thr_H. Clearly, there won't be any plot because no points will satisfy this condition. In this case, even for circular variables, we should have (-inf<=LST<inf). 
![image](https://user-images.githubusercontent.com/39411276/112336662-2dc84180-8cb5-11eb-8a8d-3fe87ee7b1ab.png)

**Comment by onyb** [comment]
With the recent changes (probably as of last release), I believe this shouldn't be an issue anymore. Can you please try again?

Here's the mapping function for the same dataset and breakpoints as in the description:

![WT_10](https://user-images.githubusercontent.com/3684187/117308057-701e9a00-ae81-11eb-9ba6-94ba4e15c0c9.png)

I found a bug in circular breakpoints validation that prevented us from having the default range as the breakpoints. This is fixed, and will be available in the next release:

<img width="1297" alt="Screenshot 2021-05-06 at 20 16 01" src="https://user-images.githubusercontent.com/3684187/117318269-8bda6e00-ae8a-11eb-802f-3405e0fc795e.png">

**Comment by onyb** [comment]
Should be fixed as of [v0.28.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.28.0). Please reopen if this is not the case.
