### ISSUE TITLE
Write the mapping functions title in 2 lines be able to include all the predictors

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#170]
Currently, the mapping functions only have one line in the title and if we have many predictors, the title is not plotted completed and we miss some information from some predictors. 
One idea could be to allow plotting 2 or 3 lines in the title if necessary, so we can see the range values from all the predictors. I attach a mapping function example with this issue. 
![WT_220000000000000](https://user-images.githubusercontent.com/69871426/112870361-0824a900-90b6-11eb-97ae-505baea0a322.png)

**Comment by onyb** [comment]
Pushed a fix directly to **`v0.25.0`**. No new release is necessary.

<img width="820" alt="Screenshot 2021-04-14 at 18 24 54" src="https://user-images.githubusercontent.com/3684187/114714154-20412d00-9d32-11eb-99ba-ccf7a09c5c31.png">
