### ISSUE TITLE
Ability to merge leafs by clicking on the node

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#172]
Hi @onyb,
after a discussion today with @EstiGascon and @AugustinVintzileos, it came out that it would be very useful for them to have the possibility to merge a node with the node on the left (like we do in the table) via a certain combination of clicks on the node to merge. The merge on the table works fine, but when there are many WTs, it can be confusing which nodes to merge, and it is very error-prone. As we don't have an undo button, this would help the user to make fewer mistakes. 
I put this as priority 1 because even if this is an enhancement and there are other ways to do the same job, Esti and Augustin do need this feature as soon as possible to do their job faster and smoothly.
Cheers, 
Fatima

**Comment by onyb** [comment]
Fixed in [v0.25.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.25.0).
