### ISSUE TITLE
Merging WTs

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#174]
Hi Anirudha,

the new way to merge the WTs is really good. Thanks for the changes!

However, I noticed that with the new way we cannot merge leaves, only nodes. This is anyway wonderful because it allows us to merge groups of WTs quite quickly. 
However, if you want to merge only one leaf, it is not possible to do that on the tree but we have to go back to the table and click on the arrows and, as pointed out by @AugustinVintzileos, it can be confusing for users when there are lots of WTs. 

Would it be possible to allow also the merge of the leaves? We could merge the leaves as we do now (to the leaf on the left), and remove the arrows in the table. 
Moreover, we could call the "Merge Children" mode something more generic like "Merge nodes".

However, if some flexibility could be added, it would be nice if, for the first leaf of the node, a merge only with the right WT can be done; for the last WT, a merge only with the left WT can be done; and if we want to merge a WT in the middle, the user could choose whether to merge to the left or to the right. This would allow the user to create a different set of merges that at the moment are not allow.

What do you @onyb?

Cheers,

Fatima

**Comment by ATimHewson** [comment]
Hi Anirudha,

Yes fully agree with Fatima that the new merging tool is great! And it has undoubtedly allowed Augustin to make a lot of progress that he was struggling to make before (together with the speed issue resolution). I think my preference would be to have just one additional option of merging leaves to the left. And I myself would leave in the merge-by-arrows options in the table, which I really like (even if it is a bit cumbersome with big trees!). The two options could then be complementary in allowing the same 'action' I think. Anyway we can discuss amongst ourselves tomorrow what is the preferred way forward here, for key users.

cheers,
Tim

**Comment by FatimaPillosu** [comment]
Ok, so after discussing this with Tim he showed me that allowing merging to the left and to right won't provide more merging combinations than just merging to the left, so we just keep it as it is. Thus, summarizing:
- we leave the merge arrows in the table;
- we allow, in the decision tree, to merge also leaves (but only to the left);
- we add a message that appears on the leaves and nodes that could not be merged, so users are not confused for what reason some nodes cannot be merged (i.e. "First node in the group. Merge only to the left.");
- allow to merge the nodes that are just below the root;
Later in the day, Tim will discuss this with Esti and Augustin, so let's see if have more ideas about this.
Cheers,
Fatima

**Comment by onyb** [comment]
Fixed in [v0.28.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.28.0).
