### ISSUE TITLE
Print log file of the computations

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#176]
Hi @onyb, 

I would like to know if it is possible to print the log files of the computations that we see in the GUI or in the console.
I know it would be a very long file, but unfortunately, in the GUI and in the console it is not possible to see the entire log file and, as it just happened to me, the exact parts that you are interested in are those not displayed!

Cheers,

Fatima

**Comment by onyb** [comment]
Fixed in [v0.28.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.28.0).
