### ISSUE TITLE
Saving calibration files for operations

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#178]
Hi Anirudha,
as discussed last week, this issue comes from a request from @EstiGascon and @AugustinVintzileos.
It is about the possibility to save the calibration files for operations using only a sub-group of the predictors considered initially. 
This is a good idea so the operator can discard those predictors that were not found interesting during the research phase without the need to regrow the decision tree from scratch with only the predictors of interest to create the calibration file in operations. 
We would also need to include the creation of the point data table that creates a new point data table that contains only the predictors considered, so there won't be any confusion.
Cheers,

Fatima

**Comment by onyb** [comment]
Fixed in [v0.28.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.28.0).
