### ISSUE TITLE
Incorrect node splits

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#181]
At the moment the split has some bug because if I want to split the node highlighted in blue, the split will be applied to the node highlighted in red. Whatever node I select, the split will be always applied to the node in red. 
The split is located in the wrong place whether we use the function split of the K-S test.
Any ideas on what could have gone wrong?

![Screenshot_2021-05-19_05-45-25](https://user-images.githubusercontent.com/39411276/118757778-aab30a00-b865-11eb-901e-b3ecb04f06c6.png)

**Comment by onyb** [comment]
Fixed in [v0.28.1](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.28.1).
