### ISSUE TITLE
Final changes for version 1.0.0

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#182]
- [x] Change the name of the modes:
![Screenshot_2021-05-24_16-45-27](https://user-images.githubusercontent.com/39411276/119372681-7d27ef80-bcaf-11eb-9cf0-8eaff1bb86aa.png)
1. Simple -> Visualize leaf MF
2. Non-Collapsible -> Visualize node MF
3. Edit -> Split leaf
4. Merge Children -> Merge Node
5. Merge leaf -> Merge leaf (no change)

- [x] Correction of the Menu bar:
1. We cannot see completely the options 
![Screenshot_2021-05-24_16-54-16](https://user-images.githubusercontent.com/39411276/119373772-b2810d00-bcb0-11eb-901e-121ab1386775.png)
2. 

- [x] Modification of the "Save operation" option:
1. Change the name of the option to "Save operational calibration files"
2. I would an explanation on the meaning of the options available, e.g.
        -  Family: ecPoint family, e.g. Rainfall, Temperature
        - Version: calibration version (in SemVer 2.0.0 format)
        - Accumulation (if applicable): accumulation period for the post-processed variable, e.g. Rainfall  
3. Add on the above sub-section the name of the post-processed dataset (Dataset Name).
![Screenshot_2021-05-24_16-58-54](https://user-images.githubusercontent.com/39411276/119374322-5965a900-bcb1-11eb-997f-571da1fbe296.png)
4. Changing the name for the following options:
![Screenshot_2021-05-24_17-00-58](https://user-images.githubusercontent.com/39411276/119374600-ad708d80-bcb1-11eb-95c7-294a46925094.png)
       - Enter the numerical value to substitute the "Infinity" value: (Infinity value)
       - Enter the number of post-processed members to create for each raw member: (No. of pp members)
5. Change the name of the default directory. Instead of having "OperCalOuts_2.1.0", it would be better to have
[Family]_[Accumulation]_[DatasetName]_[Version]

- [x] Correct the headers of the FER.csv file:
          - Start with the WT code;
          - The number of the columns should start from 1 instead of 0

- [x] I would change the name of the following files to keep them concise:
        - BiasesWT -> Bias.csv
        - BreakpointsWT -> BP.csv
        - FER -> FER.csv (do not change)
        - FE -> FE.csv

- [x] Correct some aspects of the K-S test:
- [ ] 
![Screenshot_2021-05-24_17-16-22](https://user-images.githubusercontent.com/39411276/119376943-72238e00-bcb4-11eb-9141-cbd00782ffa9.png)
1. The title of the figure doesn't get updated with the data that is tested. (In this case I tested tp_acc<2 and in the figure still says from -inf to inf). If it is too difficult to correct, I would rather don't have title because it confuses the user.
2. The name of the variable that it is considered in the GUI is not correct. In the example below, I'm working with maxCape12h and the GUI it is telling me that I'm selecting cape_wa. I know the software is doing the right thing becasue in the xaxis of the graph the variable is correct (i.e. maxCape12h) but it is a visualization problem that has to be corrected to not confuse the user.
![Screenshot_2021-05-25_11-21-56](https://user-images.githubusercontent.com/39411276/119482158-70f17000-bd4b-11eb-8f08-5bea41bc308c.png)
3. Print on the graph the sample size for the WT considered, so in the case shown we would like to know how many points are in the WT cpr<0.5 and tp_acc<2.

4. Make more consistent the way we compute the biases with the way the FER and FE values are computed. See issue #185 
5. Correct issue #186

**Comment by onyb** [comment]
Fixed in [v0.29.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.29.0).
