### ISSUE TITLE
Final changes for version 1.0.0 (Not urgent, would like to have)

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#183]
- [x] We would like to eliminate the buttons that are scatter around the GUIand are replicated in the Menu bar.
- [ ] Button "Save tree as PNG" will need to be added to the menu bar.
- [x] The "Menu bar" will stay visible on top even when we scroll down. This is important when we have a very long DT.

**Comment by onyb** [comment]
Will be part of [v0.30.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.30.0).

"Save tree as PNG" cannot be moved away from the decision tree canvas for technical reasons.
