### ISSUE TITLE
Split a leaf with more than one value

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#184]
At the moment we can split a node with only one value. However, if we know that we would like to split a node with 2, 3 or more values, it would be nice to provide the user with a way to do so.
At the moment we will need to click on the node as many times as the values that we want to use. 
This could be solved if we allow the user to introduce a list of values separated by , or /.
This would be similar on how we can split a node with several values in the K-S test.

We put this as a priority two because even if it is not a bug, it would allow the user to save a lot of time in the growing of the decision tree.

**Comment by onyb** [comment]
Will be part of [v0.30.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.30.0).
