### ISSUE TITLE
Computation of the Bias for FE and FER

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#185]
Hi Anirudha, 

There is a slight problem with the biases for the FER.

At the moment, in the way the biases are computed, it can happen that for two similar MFs, the biases look very different. This can happen if there are very, for example, twice as many values in the tail bins (in red). This is not a bug, but it looks odd and should be corrected.

I discussed with Tim the approach to compute the biases for the MFs and he thinks it would be better to compute the bias as the mean of the 100 continuous FER values (those saved as csv). This would not only take care of dodgy values in the tails, but it would also be much more consistent with the way that now the FER values are presented.

This should also be applied for FE. 

I put this as priority 2 because it is not blocking anyone but it should be included in version 1.0.0. I will add it to the correspondent issue. 

Cheers,

Fatima

**Comment by onyb** [comment]
Will be part of [v0.30.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.30.0).
