### ISSUE TITLE
Variable not displayed when splitting a node

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#186]
Hi Anirudha, 
sometimes it happens that the GUI doesn't show the variable in which one wants to split the node. See the picture below:
![Screenshot_2021-05-26_17-30-21](https://user-images.githubusercontent.com/39411276/119697590-3f120380-be48-11eb-9605-d2eb97b7c636.png)

This messes up the decision tree. It is possible to go back to the previous status of the DT but it is time-consuming. The user should not be allowed to split if no variables are displayed. 

I put it in priority 2 because, although it is not blocking the work of anyone, this should be corrected for version 1.0.0.

Cheers,

Fatima

**Comment by onyb** [comment]
Fixed in [v0.29.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.29.0). The algorithm to deduce the level of the selected node was faulty.
