### ISSUE TITLE
Not possible to complete the K-S test (it happens in a random fashion)

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#187]
Hi Anirudha,

as we discussed earlier, I showed you that sometimes (in a random fashion) it is not possible to complete the K-S test.
I cannot reproduce it but I showed you the problem, so hopefully, this will be enough. 
You mentioned that this could be related to issue #186.
Hopefully, you can find a solution to this problem.

I put this issue as priority 1 because this issue can actually stop the workflow of the users (there is a workaround but it is a bit convoluted) and it must be corrected before the launch of version 1.0.0.

Cheers,

Fatima

**Comment by onyb** [comment]
Note to self: the code breaks here

https://github.com/esowc/ecPoint-Calibrate/blob/1c1faa24704843e79144f50d7d579d8d88afbbd1/ui/workflows/C/2/split/component.js#L547

**Comment by onyb** [comment]
This should normally be fixed in the [v0.29.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.29.0) release. Closing this issue for now, but if the problem persists, please feel free to reopen.
