### ISSUE TITLE
Create the verification plots also for the nodes (not only for the leaves)

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#188]
Issue suggested by @AugustinVintzileos.

It would be good if we could have the verification plots also for the nodes. At the moment if you click on a node (i.e. which is not a leaf), nothing happens.

Cheers,

Fatima

**Comment by onyb** [comment]
Will be part of [v0.30.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.30.0).
