### ISSUE TITLE
Loading breakpoints issue

### ISSUE THREAD

**Issue by AugustinVintzileos** [esowc/ecPoint-Calibrate#190]
The hierarchy of variables is not saved when saving the breakpoints. So, when relaunching the software reading the data points and loading the saved breakpoints the tree will use the hierarchy of variables of the original data point file which might have changed during the development.

**Comment by FatimaPillosu** [comment]
Hi @AugustinVintzileos, you can solve this problem by inspecting your point data table in advance and make sure the order of the predictors in the software corresponds to the order of the predictors in the point data table.
I will close this issue but if you have other questions about this topic, please feel free to reopen it. 
Cheers,
Fatima
