### ISSUE TITLE
Allow users to define units in the computations UI

### ISSUE THREAD

**Issue by onyb** [esowc/ecPoint-Calibrate#37]
Units will mainly serve two purposes:
 - Documentation
 - Assert the fact that some scaling factor was consciously applied to the computations. The user is responsible for making sure that the units correspond well to the _scaled_ values.

The units should be displayed for each computation in the metadata section of the ASCII table.

**Comment by FatimaPillosu** [comment]
Check mock-up for applications working with the units of the parameters considered.

1. In the section "Model data - Predictand", once a variable is selected as predictand, the units in which the variable is safe should be automatically displayed. This can be easily determined by interrogating the grib file. 
********************************************
Example:
data_grib = read(FileName_grib)
units = grib_get_string(data_grib,"units")
Output:
units=m (string)
********************************************

2. When it is requested to enter the minimum value to not divide by zero, it would be less error-prone to select a value correspondent to the displayed units (e.g. 0,001 if the displayed unit is meters). Then, the scale factor applied to the predictand will be automatically applied also to that threshold value. In this way, there shouldn't be inconsistencies between the different inserted values.

**Comment by FatimaPillosu** [comment]
Check mock-up for changes on how to consider variable units for the variables and the predictors in the "Predictor Computation" tab.

- When an input variable is selected in the "Input variable(s)" column, the units of that variable are displayed (see previous comment on how to interrogate the grib file).
- In the "Scaling factor" column it is possible to select a scaling factor. If it is equal to 1, no actions are taken, and the "New units" area could be pre-filled with the original units. If it is not equal to 1, the user should introduce the new units under "New units". If the user leaves "New units" empty, this should be highlighted as an error.

**Comment by onyb** [comment]
Here are the screenshots of how the new UI framework for defining computations looks like:

![1](https://user-images.githubusercontent.com/3684187/62402237-1475fd00-b587-11e9-9928-bb829954b1c8.png)



![2](https://user-images.githubusercontent.com/3684187/62402239-15a72a00-b587-11e9-8480-b3b24609cbba.png)
