### ISSUE TITLE
Visual makeover of ecPoint-PyCal

### ISSUE THREAD

**Issue by onyb** [esowc/ecPoint-Calibrate#51]
We want to make the splash screen of the software much more attractive.

- [x] Update ECMWF logo
- [x] Add a background animation to the splash screen
  * See https://codepen.io/ste-vg/pen/Gqakbo
- [ ] Think about a ecPoint-PyCal logo
- [ ] ???

**Comment by onyb** [comment]
**Result:**

![](https://user-images.githubusercontent.com/3684187/59980157-28c2f380-95f2-11e9-8086-aa7f7b78990e.jpeg)

**Comment by FatimaPillosu2019** [comment]
The graphics team at ECMWF have got involved. Let's wait for their answer.

**Comment by onyb** [comment]
This is how the latest version of the splash screen looks like:

![v2](https://user-images.githubusercontent.com/3684187/62405766-ed78f480-b5a1-11e9-98ce-589a7dbd12cd.png)

Closing this, since there are no new planned visual changes left to be done.
