### ISSUE TITLE
Allow downloading a snapshot of the decision tree state

### ISSUE THREAD

**Issue by onyb** [esowc/ecPoint-Calibrate#53]

**Comment by FatimaPillosu2019** [comment]
More than a "snapshot", I was thinking on a printable version for example in pdf or jpeg.
I don't know if that would be possible or how complicated it is.  Let's discuss that.
However, it would be nice to have this option in the case, for example, a user wants to save a picture of the DT to add it in a presentation. An example could be this:

![DT](https://user-images.githubusercontent.com/50220672/59982839-2374a180-9610-11e9-9693-8ce9b2ca7163.jpg)

If I remember well, at the moment, the nodes of the DT contain only the name of the variables and the breakpoints. However, It would be nice if the printable of the DT could have the simplified version of the MFs as this is the important graphical part of interest for readers.
