### ISSUE TITLE
Implement missing computations

### ISSUE THREAD

**Issue by onyb** [esowc/ecPoint-Calibrate#55]
#### Computations that it seems are not implemented yet:

- [x] Instantaneous field
- [x] Maximum field
- [x] Minimum field
- [x] Average field
- [x] 24h solar radiation

#### Computations that are implemented and are correct:
- [x] Accumulated field
- [x] Ratio field

#### Computations that are implemented but are not correct:
- [x] Weighted Average Field
- [x] Vector module

**Comment by FatimaPillosu** [comment]
Hi, we must remember to implement the calculations for the FE (Forecast Error) and not only the FER! The calculations are in the png provided last year.

**Comment by FatimaPillosu** [comment]
After yesterday's meeting, Tim has suggested the following changes for these computations:
- Ratio field: we need to deal with those cases in which the denominator is equal to 0. If that happens, then set the value as missing_value. Currently the computations fail.
- Weighted average: we assume that the weighted average is computed using three values. Tim suggests we also include the possibility to have a weighted average computed using 5 values. Maybe, in the list of possible computations we can have "Weigthed Average - 3 Values" and "Weigthed Average - 5 Values". We could be more flexible having an extra parameter (e.g. number of values to compute the wa) but, if that is to complicated, I think we can do for now with having only this two possibilities.

**Comment by onyb** [comment]
I realized that Ratio Field isn't doing what it means. See the snippet below: https://github.com/esowc/ecPoint-PyCal/blob/53330c3145e8a45cd773ff3d19ccd95dc27a6181/core/processor/__init__.py#L316-L332

As you can see, the dividend and the divisor are not the computed values, but they are the matching nearest gridpoint values. This was done mainly to accommodate the fact that ratio field is mainly for calculating `CPR`, which is not `CP / TP`, but actually `CP_obs / TP_obs`.

where,
`CP` = accumulated field for `CP`
`TP` = accumulated field for `TP`
`CP_Obs` = observation values matching nearest gridpoint of `CP` (accumulated field)
`TP_Obs` = observation values matching nearest gridpoint of `TP` (accumulated field)

As a consequence of the above behavior, the computation for Ratio Field is NOT supposed to fail because `TP_obs` has a minimum value constraint.

Happy to go over this during a meeting in detail, and see why it's failing for you.

**Comment by onyb** [comment]
Regarding support for "Weighted Average - 5 values", it's already implemented. It designed to handle arbitrary number of inputs (`3`, `5`, whatever). Here's the code:

https://github.com/esowc/ecPoint-PyCal/blob/53330c3145e8a45cd773ff3d19ccd95dc27a6181/core/computations/utils.py#L15-L28

@FatimaPillosu Did you notice any bug in the computation?

**Comment by FatimaPillosu** [comment]
Here I upload the metview macro that contains all the functions (see section "Functions" at the bottom of the macro) for the computations, and some examples of the computations (see section "Computations" at the top of the macro). They have been checked and all of them are correct. Please, follow this to check whether you are computing everything in the right way.
Please, note that the file have been save with the "txt" extension only to allow GitHub to upload the file here. But it is actually a Metview macro.

[AllFunc_mv.txt](https://github.com/esowc/ecPoint-PyCal/files/3446926/AllFunc_mv.txt)
