### ISSUE TITLE
Add field to store unit for observation values

### ISSUE THREAD

**Issue by onyb** [esowc/ecPoint-Calibrate#60]
If the user is changing the scaling factor of the predictor, we should ask him/her to enter the new unit, and then match it with the one defined in the observational data section.

Do this only for the predictand variable.

Also rename "Pre-computed variable" to "Predictand variable (pre-computed)".

**Comment by FatimaPillosu** [comment]
See the following mock up:
![ObservationalData_MockUp](https://user-images.githubusercontent.com/39411276/62138184-22095980-b2df-11e9-978c-1929e12fbf56.PNG)
