### ISSUE TITLE
Move discretization and start time field to General Parameters

### ISSUE THREAD

**Issue by onyb** [esowc/ecPoint-Calibrate#63]
@FatimaPillosu Please feel free to add more details.

We want to have the following 3 new fields:
 - start time
 - end time
 - discretization

These new fields are supposed to be used with forecast data, **NOT** observations.

**Comment by FatimaPillosu** [comment]
Please, follow the following mock-up:
![ModelData_GeneralParameters_MockUp](https://user-images.githubusercontent.com/39411276/62138414-84faf080-b2df-11e9-957f-a759689ebf91.PNG)
