### ISSUE TITLE
Allow to merge leafs in the decision tree and WT codes

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#70]

**Comment by FatimaPillosu** [comment]
Please look for options to be able to merge leafs in the decision tree, and after that update the name of the weather types, generated with the Matlab function [WT_Code.txt](https://github.com/esowc/ecPoint-Calibrate/files/3471136/WT_Code.txt)

*************
**Example on how to run WT_Code**

> % Load the .mat file with the breakpoints for the predictors
`load( 'BreakPoints.mat')` %uploads the matrixes thrH (214X5) and thrL (214X5) because we have in this example 214 WTs and 5 predictors.

> %Generate the WT Codes
`WT_arr = WT_Code(thrL,thrH);`

**Example of the WT_Code output**
WT_arr = 
    '11111'
    '11112'
    '11120'
    '11211'
    '11212'
    '11220'
    '11230'
    '12111'
    '12112'
    '12113'
    '12120'
    '12130'
    '12211'
    '12212'
    '12213'
    '12221'
    '12222'
    '12230'
    '13111'
    .....

**Comment by onyb** [comment]
Shipped as of **v0.6.0**.
