### ISSUE TITLE
Creation of the output file BreakPointsWT.txt

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#75]
This is one output from the calibration software to be used in the production of the post-processed forecasts.
It requires to save in an ascii file the deployed table containing all the WT's breakpoints. If it is possible, please maintain the same structure. However, if it is difficult, change it as you require, and then I will adapt the operational code.
*************************************
**BreakPointsWT.txt** Example
[BreakPointsWT.txt](https://github.com/esowc/ecPoint-Calibrate/files/3471244/BreakPointsWT.txt)

**Comment by onyb** [comment]
@FatimaPillosu Can you upload the corresponding Matlab code too?

**Comment by onyb** [comment]
Here's how it looks like:

```
WT code,cpr_thrL,cpr_thrH,tp_acc_thrL,tp_acc_thrH,wspd_thrL,wspd_thrH,cape_wav_thrL,cape_wav_thrH,sr24h_thrL,sr24h_thrH
11001,-inf,0.25,-inf,2.0,5.0,20.0,-inf,inf,-inf,70.0
11002,-inf,0.25,-inf,2.0,5.0,20.0,-inf,inf,70.0,275.0
11003,-inf,0.25,-inf,2.0,5.0,20.0,-inf,inf,275.0,inf
11101,-inf,0.25,-inf,2.0,20.0,inf,-inf,inf,-inf,70.0
11102,-inf,0.25,-inf,2.0,20.0,inf,-inf,inf,70.0,275.0
11103,-inf,0.25,-inf,2.0,20.0,inf,-inf,inf,275.0,inf
```
