### ISSUE TITLE
Allow negative "Addition factor" in Computations tab

### ISSUE THREAD

**Issue by onyb** [esowc/ecPoint-Calibrate#83]
For example, a user should be able to specify `-3` in the addition factor.

**Comment by FatimaPillosu** [comment]
This is an error as there might be cases in which the user might want to subtract such factor.

**Comment by onyb** [comment]
Fixed in [v0.11.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.11.0). Closing this issue as it has been validated in #121.
