### ISSUE TITLE
Problems with the "Instantaneous field" when considering an "accumulated predictand"

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#95]
It is not clear why "2" fields are selected, and how are they processed to give just one value. This can trigger serious errors. It needs clarification.

This issue does not appear when considering an "Instantaneous" predictand.

**Comment by FatimaPillosu** [comment]
I think the way to solve this and eliminate any ambiguity is, instead of having one computation call "Instantaneous" which how it is related to the accumulation period of the predictand, we can have three new computations:
- instantaneous (Beginning of the Period)
- instantaneous (Middle of the Period)
- instantaneous (End of the Period)

**Comment by onyb** [comment]
Fixed in [v0.14.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.4.0).
