### ISSUE TITLE
Make the FER.csv and the FE.csv file more legible

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#96]
The csv file is not saved in a very legible format. To understand the values in FER.csv, the table should have a first column that contains the WT codes, and a first row that counts the number of FER values that are present for each WT. The FER values should also contain fewer decimal digits, no more than 3 for example.
Same considerations should be done for the FE.csv file.

**Comment by onyb** [comment]
@FatimaPillosu Here's how it looks it now after my change (opening the CSV on a spreadsheet software). Please let me know if this is what you had in mind.

Column A represents the WT codes. Row 1 is the index, which ends at the number of columns requested by the user on the GUI.

<img width="956" alt="Screenshot 2020-10-25 at 16 55 29" src="https://user-images.githubusercontent.com/3684187/97112152-fb54f100-16e2-11eb-9217-b03da71334f4.png">

<img width="939" alt="Screenshot 2020-10-25 at 16 55 46" src="https://user-images.githubusercontent.com/3684187/97112154-fbed8780-16e2-11eb-8a7e-170df7fcefa6.png">

**Comment by FatimaPillosu** [comment]
@onyb , this is perfect. Exactly how I had it in mind.
Cheers,
Fatima
