### ISSUE TITLE
Correction of parameters selection for "Daily Solar Radiation" computation

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#97]
When the computation "Daily Solar Radiation" is selected, it would good I can't allow the user to select any other parameter but solar radiation, or at least raise a flag warning the user to select only solar radiation parameters.

**Comment by onyb** [comment]
I implemented this feature, but please note that it is tied to the directory name of the solar radiation predictor, which may or may not be `sr`. If the directory name is something other than `sr`, we fallback to the default behaviour of displaying the entire list in the dropdown.

<img width="1143" alt="Screenshot 2020-11-02 at 01 16 34" src="https://user-images.githubusercontent.com/3684187/97819473-0ee6f580-1ca9-11eb-9aa5-c04189501137.png">

**Comment by FatimaPillosu** [comment]
Hi Anirudha,
this is fantastic! 
Regarding the naming problem, could it be possible to read the name of the variable in the grib file (like in the same way you read the units) and display in the list only the variables that contain "solar" and "radiation" in the variable name? This would solve the problem because however is the name of the directory, what it counts is the name for the variable in the grib file.

**Comment by FatimaPillosu** [comment]
Maybe, we can allow the user to select between all the parameters, but when one is selected, the GUI displays the name of the variables contained in the grib file in the relevant directory. 
A message in a bright colour could appear asking the user to check whether that is the variable that wants effectively to use to calculate 24h solar radiation.
