### ISSUE TITLE
Unwanted decimal points in the MFs

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#98]
The number on the top of each bar represent absolute frequencies, and therefore they have to be integers. it is not clear why they appear as decimals. 
![image](https://user-images.githubusercontent.com/39411276/94737775-5145ab80-0366-11eb-9b9d-e7095391eab8.png)

**Comment by FatimaPillosu** [comment]
It would be also nice to have printed somewhere in the plot the total number of observations that contributed to this WT (i.e. the sum of the values on top of the bars).

**Comment by onyb** [comment]
This is indeed a bug, but I couldn't reproduce it on my side. Perhaps it was in an old version? If you could upload the specific point data table that you used for the decision tree, that'd help me figure out the issue.

Also, I added the total number of observations:
![WT_10000](https://user-images.githubusercontent.com/3684187/97818806-e957ed00-1ca4-11eb-8142-a6336b9414ee.png)

**Comment by ATimHewson** [comment]
Thanks for this Anirudha. Nice to see the total number of obs marked! Fatima should be able to provide the offending point data table.

**Comment by FatimaPillosu** [comment]
Hi Anirudha, 
the point data table that I used and creates the problems are already in my Google Drive:
https://drive.google.com/drive/folders/1veK7iz-RQsjqLAepUddVOMnjtukdnIjg?usp=sharing
Only you can open this link.

**Comment by FatimaPillosu** [comment]
I reopen the issue because I have seen the problem again. I didn't manage to reproduce it though.
Please, let me know if you can reproduce it on your side, but this is a very random problem. 
If you can't, I will try to check again.

**Comment by FatimaPillosu** [comment]
This problem was solved in prior releases.
